apiVersion: v1
kind: Service
metadata:
   name: pg-node-service
spec:
   clusterIP: None
   ports:
   - protocol: TCP
     port: 5432
     targetPort: 5432
   selector:  
     name:  example
   type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pg-node-service
subsets:
  - addresses:
    - ip: 10.0.0.140
    ports:
      - port: 5432