apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 4Gi # Adjust the size according to your needs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default # Match this with your PVC or set it to a specific storage class
  local:
    path: /mnt/data # Path to the directory on your node; adjust as needed
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nano-pi # Replace with the name of your Raspberry Pi node
