apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: application
      component: api
  template:
    metadata:
      labels:
        app: application
        component: api
    spec:
      imagePullSecrets:
        - name: dockerconfigjson
      containers:
        - name: api
          image: "ghcr.io/joeldevelops/node-energy-k8"
          resources:
            limits:
              memory: 600Mi
              cpu: 415m
            requests:
              memory: 300Mi
              cpu: 200m
          ports:
            - name: api
              containerPort: 3000

          livenessProbe:
            httpGet:
              path: api/v1/liveness
              port: api
          startupProbe:
            httpGet:
              path: api/v1/readiness
              port: api
            failureThreshold: 6
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: env
          env:
            - name: K8_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
