namePrefix: rpi-

commonLabels:
  env: production
  provider: kustomize

namespace: napi

generatorOptions: {}

configMapGenerator:
  - behavior: merge
    envs:
      - application.env
    name: node-env

images:
  - name: ghcr.io/joeldevelops/node-energy-k8
    newTag: v0.0.1

resources:
  - ../../base
  - ingress.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
