name: build_and_deploy

on: [push]

env:
  CI_REGISTRY_IMAGE: ghcr.io/joeldevelops/node-energy-k8

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Setup
      - uses: actions/checkout@v3

      # we need to replace `/` in the branch name with `-` to make it compatible with docker registry tags
      - name: serialize branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${{ github.ref_name }} | sed 's/\//-/g')"
        id: serialize_branch

      # Build Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CI_REGISTRY_IMAGE }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.CI_REGISTRY_IMAGE }}:${{ steps.serialize_branch.outputs.branch }}
            ${{ env.CI_REGISTRY_IMAGE }}:${{ github.sha }}
          labels: ${{ steps.serialize_branch.outputs.branch }}
          # System is deployed to a raspberry pi, so we need to build for that
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max